<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="40846" started-at="2021-07-14T01:17:03 IST" finished-at="2021-07-14T01:17:43 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="40846" started-at="2021-07-14T01:17:03 IST" finished-at="2021-07-14T01:17:43 IST">
      <class name="AllureReporTestNGwithSelenium.AllureReporTestNGwithSelenium.CustomizationAllure">
        <test-method status="PASS" signature="setUp()[pri:0, instance:AllureReporTestNGwithSelenium.AllureReporTestNGwithSelenium.CustomizationAllure@62e8f862]" name="setUp" is-config="true" duration-ms="28823" started-at="2021-07-14T01:17:03 IST" finished-at="2021-07-14T01:17:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="validateTitle()[pri:1, instance:AllureReporTestNGwithSelenium.AllureReporTestNGwithSelenium.CustomizationAllure@62e8f862]" name="validateTitle" duration-ms="179" started-at="2021-07-14T01:17:32 IST" description="Validaton of Title" finished-at="2021-07-14T01:17:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitle -->
        <test-method status="PASS" signature="validateBlogIsOpening()[pri:2, instance:AllureReporTestNGwithSelenium.AllureReporTestNGwithSelenium.CustomizationAllure@62e8f862]" name="validateBlogIsOpening" duration-ms="6595" started-at="2021-07-14T01:17:33 IST" finished-at="2021-07-14T01:17:39 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateBlogIsOpening -->
        <test-method status="SKIP" signature="validateSkippingTest()[pri:3, instance:AllureReporTestNGwithSelenium.AllureReporTestNGwithSelenium.CustomizationAllure@62e8f862]" name="validateSkippingTest" duration-ms="5" started-at="2021-07-14T01:17:39 IST" finished-at="2021-07-14T01:17:39 IST">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test
at AllureReporTestNGwithSelenium.AllureReporTestNGwithSelenium.CustomizationAllure.validateSkippingTest(CustomizationAllure.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateSkippingTest -->
        <test-method status="FAIL" signature="verifyHomeLink()[pri:4, instance:AllureReporTestNGwithSelenium.AllureReporTestNGwithSelenium.CustomizationAllure@62e8f862]" name="verifyHomeLink" duration-ms="59" started-at="2021-07-14T01:17:39 IST" finished-at="2021-07-14T01:17:39 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Create a maven project in eclipse] but found [HOOMEEPage]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Create a maven project in eclipse] but found [HOOMEEPage]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at AllureReporTestNGwithSelenium.AllureReporTestNGwithSelenium.CustomizationAllure.verifyHomeLink(CustomizationAllure.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomeLink -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:AllureReporTestNGwithSelenium.AllureReporTestNGwithSelenium.CustomizationAllure@62e8f862]" name="tearDown" is-config="true" duration-ms="3535" started-at="2021-07-14T01:17:40 IST" finished-at="2021-07-14T01:17:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- AllureReporTestNGwithSelenium.AllureReporTestNGwithSelenium.CustomizationAllure -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
